### ISSUE TITLE
MySQL driver does not have default import

### ISSUE THREAD

**Issue by woowenjun99** [sqlc-dev/sqlc-gen-typescript#25]
When I use the MySQL driver, sqlc generates

```ts
import mysql, { RowDataPacket } from "mysql2/promise";
```

However, there is no default import for mysql. Changing to the following works:

```ts
import * as mysql from "mysql2/promise";
```

**Comment by kyleconroy** [comment]
So I have an end-to-end test to ensure that the generated code works with MySQL. You can see the [import I'm using there](https://github.com/sqlc-dev/sqlc-gen-typescript/blob/main/examples/node-mysql2/src/db/query_sql.ts) works just fine. Can you help me understand why my example works and yours doesn't?

**Comment by yshrsmz** [comment]
@woowenjun99 I can also confirm that it's working fine in its current form.
How do you configure your `tsconfig.json`?

**Comment by woowenjun99** [comment]
Hi try using "postgresql" as the engine for MySQL, it should produce the result
