### ISSUE TITLE
Generated insert method takes in string but returns integer

### ISSUE THREAD

**Issue by woowenjun99** [sqlc-dev/sqlc-gen-typescript#3]
- In my table, I have a field that is of type `INTEGER`. 
- When I generate the code that takes in the field to be inserted into the database, I need to specify it as a string.
- Upon INSERT, the value is inserted into the database as a number.
- My SQLC command for the insert expects a `return :one` and the same field returns an integer.

## Example

```sql
-- name: CreateOne :one
INSERT INTO table (something) VALUES ($1) RETURN *;
```

The function `createOne` is generated, but the type for `something` field during insert is incorrect (in this case a string rather than an integer). However, the return type is a number which is correct.

Even though it is not a big issue, it causes some inconvenience.

**Comment by kyleconroy** [comment]
Could you share your schema and sqlc.yaml? I need the CREATE TABLE statement to help debug the issue.

**Comment by kyleconroy** [comment]
Can you try casting $1 to text? I think this will give you the string input type you're looking for.

```sql

-- name: CreateOne :one

INSERT INTO table (something) VALUES ($1::text) RETURN *;

```

**Comment by woowenjun99** [comment]
Thanks for the quick reply! My schema looks something like this:

```sql
CREATE TABLE "products" (
    "id" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,

    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);
```

What was generated looks something like this:
```ts
export interface CreateProductArgs {
    id: string;
    quantity: string;
}

export interface CreateProductRow {
    id: string;
    quantity: number;
}
```

**Comment by kyleconroy** [comment]
@woowenjun99 Thanks for providing your schema. I misunderstood the issue at first but have now reproduced it locally.

**Comment by kyleconroy** [comment]
Can you confirm that things are now working with 0.1.2?

```yaml
version: '2'
plugins:
- name: ts
  wasm:
    url: https://downloads.sqlc.dev/plugin/sqlc-gen-typescript_0.1.2.wasm
    sha256: f8b59cdd78b35fae157a95c5813cb09b1ebdd9a31acf2d7015465539986ccd2b
```
