### ISSUE TITLE
Bug with sqlc generating a mysql query

### ISSUE THREAD

**Issue by MohammadIsmaill** [sqlc-dev/sqlc-gen-typescript#34]
<img width="863" alt="image" src="https://github.com/sqlc-dev/sqlc-gen-typescript/assets/62969043/824e0361-9374-4e49-9a82-85325b1816ca">

there is no place to put email in function

**Comment by yshrsmz** [comment]
use `?` instead in mysql.

```sql
select id, name, email, password, created_at from user where email = ? limit 1;
```

**Comment by MohammadIsmaill** [comment]
yeah it worked ! Thank you
