### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by jlarmstrongiv** [sqlc-dev/sqlc-gen-typescript#5]
It would be nice if it worked with both [@sqlite.org/sqlite-wasm](https://www.npmjs.com/package/@sqlite.org/sqlite-wasm) in the browser and [better-sqlite3](https://www.npmjs.com/package/better-sqlite3) in node

It may be possible to support many dialects.  See https://github.com/subframe7536/kysely-sqlite-tools for an example

**Comment by PorcoRosso85** [comment]
+1

**Comment by asterikx** [comment]
+1 for supporting SQLite and [libSQL](https://github.com/tursodatabase/libsql) (Turso)

**Comment by kyleconroy** [comment]
I merged #11 which adds beta support for SQLite. Please play around with it and file any issues where it breaks.
