### ISSUE TITLE
Row is possibly undefined

### ISSUE THREAD

**Issue by woowenjun99** [sqlc-dev/sqlc-gen-typescript#6]
This is not a bug but more of an annoying issue. Upon generating the TypeScript file, there is an issue where `row` might be undefined during `const row = result.rows[0];`. One simple solution would be to typecast by editing the generated file, but it is not really ideal. Would there be a better solution to this?

<img width="278" alt="Screenshot 2024-01-03 at 12 39 57 AM" src="https://github.com/sqlc-dev/sqlc-gen-typescript/assets/88195289/99515338-9648-4227-a63b-2f9c9b05e97c">
<img width="933" alt="Screenshot 2024-01-03 at 12 39 52 AM" src="https://github.com/sqlc-dev/sqlc-gen-typescript/assets/88195289/960c898b-0e7d-4b6e-9517-a20f6eb15f5f">

**Comment by kyleconroy** [comment]
We can update the generated code with an additional `if` statement. Can you edit the code to add the following `if` statement and see if things are fixed?

```ts
    if (result.rows.length !== 1) {
        return null;
    }
    const row = result.rows[0];
    if (!row) {
        return null;
    }
    return {
        id: row[0],
        name: row[1],
        bio: row[2]
    };
```

**Comment by woowenjun99** [comment]
Yeap adding in the additional if statement does remove the error
