### ISSUE TITLE
add "Code generated by sqlc. DO NOT EDIT." header comment

### ISSUE THREAD

**Issue by yshrsmz** [sqlc-dev/sqlc-gen-typescript#9]
to prevent devs from editing the generated file.

**Comment by yshrsmz** [comment]
I can achieve this behavior by just modifying [here](https://github.com/sqlc-dev/sqlc-gen-typescript/blob/main/src/app.ts#L277)

```diff
   const printer = createPrinter({ newLine: NewLineKind.LineFeed });
-  let output = "";
+  let output = "// Code generated by sqlc. DO NOT EDIT.\n\n";
   for (let node of nodes) {
     output += printer.printNode(EmitHint.Unspecified, node, resultFile);
     output += "\n\n";
   }
   return output;
```

But I'm not sure if it's OK or should be handled in another place.

**Comment by kyleconroy** [comment]
The Go code generator adds the header by default and you can't turn it off. I think it's a good idea to always add it.
